# Generated by Django 3.0.6 on 2020-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200530_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
