# Generated by Django 3.0.8 on 2020-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200717_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
